### PR TITLE
Try both gray and indexed low depths

### LINKED ISSUE #515: Chooses 2-bit grayscale over 1-bit indexed
When I optimize a 4096x4096, 4x8-bit RGBA image where each pixel is either transparent or opaque black, it is output as 8-bit grayscale, even though it could actually be 1-bit indexed (as it is when the opaque pixels are the same non-gray color). Likewise when the opaque pixels are 0xaaaaaa, it is output as 2-bit grayscale, and 0x515151, 8-bit grayscale. Only white seems to avoid this issue.

### PR DESCRIPTION
**Pull request by andrews05**
Changes the depth reduction logic to also try low-depth indexed even if we already achieved low-depth grayscale, ~~but only if we can do it even lower than the grayscale~~.

Fixes #515

### CODE REVIEW

**Comment by ace-dent** [comment]
There are rare situations where higher bit-depth indexed can beat lower bit-depth grayscale. In part because: 1. freedom to optimise the first colour entry (explained in original issue); 2. 8-bit symbols may form a more compressible data stream. The assumptions in the PR are quite reasonable for most cases. However, it'd be nice if there was a `max` level that tested all these combinations (color type & bit depths).

**Comment by andrews05** [comment]
8-bit indexed can indeed be better than grayscale and this is well covered already.

The PR is specifically for low depths (1,2,4), where indexed will necessarily reach equal or lower depth than grayscale. There was a missed reduction where the indexed might have reached a lower depth than the grayscale but we weren't checking. I haven't actually found such an image in practice though (I had to create one synthetically to test), which is why I've been so slow to add this.

It is theoretically possible that indexed could be better even if it isn't lower (e.g. 2-bit indexed vs 2-bit grayscale), but it seems unlikely. Maybe I should test that further...

**Comment by andrews05** [comment]
I've update this to attempt both reductions, but to skip the evaluation if the data comes out the same.

**Review by AlexTMjugador — APPROVED** [review]
I've reviewed this PR a bit some weeks ago, but didn't submit a review. Now that I get back to it, I think it looks good :+1:

**Pull request merged**
