### PR TITLE
Further small reduction improvements

### LINKED ISSUE #72: Implement possible size optimizations from Color Type from TruePNG
https://css-ig.net/articles/truepng.php

> Colortype reductions
> TruePNG does some other trials that are not done automatically (or not done at all) by other tools:
>
- [x] TruePNG can test grayscale if image is graylevel
- [ ] it tests tRNS chunk instead of alpha channel if applicable
- [x] it reduces truecolor+alpha to grayscale+alpha
- [ ] it can choose truecolor, even if image contains less than 256 colors (or less)
- [ ] TruePNG can encode to palette mode even if image is graylevel

### LINKED ISSUE #418: Leanify tool provides better lossless compression than Oxipng.
https://github.com/JayXon/Leanify build from the source.
`leanify -p` vs `oxipng -arvZ -o max --strip all --fix`. Not all images were better compressed after using leanify on them, but overall results were better than Oxipng ones.

Assets in this repository were used for this test https://github.com/Waoweens/WaoTweaks.

### PR DESCRIPTION
**Pull request by andrews05**
The primary purpose of this development is to add a new "reduction" trial for indexed to RGB/grayscale. Implementing this revealed a couple of flaws though, so it ended up a bit bigger:
- The size estimation added in #499 was helpful but I neglected to make use of it outside of the evaluator. I've made changes to take this into account for primary compression trials as well.
- The palette wasn't consistently reduced, which could cause the estimated size to be inflated. I've separated palette reduction and sorting into two different functions. The reduction is unconditional and won't be evaluated. This means truncation of the palette is no longer necessary on output, which simplifies things. "palette_8_should_be_palette_8.png" compresses better now as it prefers the unsorted palette which wasn't previously being reduced.

With both those sorted, the new indexed conversion is able to achieve some small gains. The previously unused test file "palette_8_should_be_grayscale_8.png" now successfully converts to grayscale, saving 141 bytes 🙂 (yeah okay, only 1%).
Note that conversions to a higher bpp (excludes grayscale) will only be evaluated for small files, so performance impact will be minimal.

Closes #418, with further improvements to the results there.

[edit] Updated with support for grayscale to indexed evaluation, so it can convert in either direction. This closes #72, checking off the final item 5.

### CODE REVIEW

**Review by kornelski — APPROVED** [review]

**Comment by andrews05** [comment]
Just adding some better tests, will update shortly

**Comment by andrews05** [comment]
Gah, I got the background conversion wrong in indexed_to_channels. Fixed now.

**Comment by shssoichiro** [comment]
Not surprisingly, the Raw API merge caused a conflict with this PR 😅

**Comment by andrews05** [comment]
@shssoichiro Sorted 🙂

**Review by shssoichiro — APPROVED** [review]
Thanks!

**Pull request merged**
