### PR TITLE
Fix name capitalization

### PR DESCRIPTION
**Pull request by karlhorky**
Hi, thanks for Oxipng!

I saw further down in the readme that Oxipng was being used in the middle of a sentence with a capital O, so I adjusted the other lowercase usages (other than the usages in backticks, which may instead refer to the command line program itself) from "oxipng" to also use "Oxipng"

### CODE REVIEW

**Comment by ace-dent** [comment]
Need to check in with @shssoichiro what the naming intention is! :-)

**Comment by AlexTMjugador** [comment]
Oddly enough, I tend to capitalize OxiPNG like that, not as Oxipng or oxipng... :joy:

**Comment by andrews05** [comment]
@AlexTMjugador Personally, I think that makes it look too similar to OptiPNG 😆

**Comment by ace-dent** [comment]
Not sure if it's open to voting(!?)... but my preference is `oxipng` and capitalised at the start of a sentence.

**Comment by karlhorky** [comment]
> `oxipng` and capitalised at the start of a sentence.

Usually mixing like this will lead to style confusion - often it's better to have a single, strong capitalization style for a brand name and stick with it (regardless of where the word is used in the sentence).

However, that's not to say that the brand name for the project / ecosystem can't be styled differently than the brand name for the command line interface, for example:

1. Oxipng (capital O, everything else lowercase) for the brand name for the project / ecosystem / anything else
2. `oxipng` for the brand name for the command line interface program

**Comment by AlexTMjugador** [comment]
I'm still unsure about the preferred capitalization for the project, but I think we can all agree that maintaining consistency within a single document makes it look tidier. Therefore, I'm merging this PR as-is. At the moment, I do not intend this PR to imply that a given capitalization style should be preferred over others, though.

**Comment by karlhorky** [comment]
@AlexTMjugador thanks for the consideration, review and merge!

**Pull request merged**
