### PR TITLE
Full switch to Libdeflater

### LINKED ISSUE #422: Support forwarding `freestanding` feature to `libdeflater` for WebAssembly
I'm not sure if this is already possible, but I couldn't find a way to enable the [`freestanding` feature of libdeflater](https://github.com/adamkewley/libdeflater#compile-time-features) apart from adding it as a dependency next to oxipng and setting that feature (which is relying on Cargo deduplicating the two instances of `libdeflater` which isn't guaranteed?).

```
oxipng = {version = "5.0.0", features = ["libdeflater", "zopfli"]}
libdeflater = {version = "0.7", features = ["freestanding"]}
```

So maybe oxipng should expose a `freestanding` feature that  is then forwarded to its `libdeflater` dependency?

This is needed to build for the wasm32-unknown-unknown target.

### LINKED ISSUE #454: Allow setting libdeflate compression level
Using the `-D` option to switch to libdeflate appears to default to the highest compression level (12). This is relatively slow for very little gain over some lower levels (say, 10). It would be helpful to be able to set the level with the same `--zc` option as zlib.

As a side note, I ran a benchmark of `-o 1 -D` vs `-o 3`. The result was (coincidentally) identical total savings over my test set, but the libdeflate one performed over twice as fast. Some experiments may be warranted, but I think with a level of 10 it could be both smaller and faster than zlib, potentially replacing it as the default compressor.

### PR DESCRIPTION
**Pull request by andrews05**
Libdeflate has improved (since first added in #203) to the point where it almost always compresses significantly better than even cloudflare-zlib, and while slower at its highest levels it generally ends up faster in oxipng due to not needing to test 4 different "strategies". It definitely seems worth fully switching to libdeflate instead of zlib, as benchmarks below will show.

This PR is fairly large and includes the following changes:
- Changes all compression to libdeflater, adjusting default options as appropriate (see below).
- Changes all decompression to libdeflater. This is significantly faster but has little impact on total speed.
- Changes crc32 checksums to libdeflater's implementation. As above, this is also significantly faster but still has little impact on total speed.
- Removes dependencies on cloudflare-zlib, miniz-oxide, and crc.
- Removes redundant `-D`, `--zs` and `--zw` options.
- ~~Changes evaluation to only check filter 0 instead of both 0 and 5. This is faster and made zero difference to output in the files I tested.~~
- Adds `freestanding` feature to expose `libdeflater/freestanding`. (Closes #422).

The new optimisation levels are as follows, including a reinstated level 4:
```
-o 0   =>  --zc 5 --nz          (0 or 1 trials)
-o 1   =>  --zc 10              (1 trial, determined heuristically)
-o 2   =>  --zc 11 -f 0,5       (2 trials)
-o 3   =>  --zc 11 -f 0-5       (6 trials)
-o 4   =>  --zc 12 -f 0-5       (6 trials; same as `-o 3` for zopfli)
-o 5   =>  --zc 9-12 -f 0-5     (24 trials; same as `-o 3` for zopfli)
-o 6   =>  --zc 1-12 -f 0-5     (72 trials; same as `-o 3` for zopfli)
```
I benchmarked against the files in the test folder, totalling 23511320 bytes (excluding the >30MB `issue-167.png` which takes forever and skews the results).

Level | Zlib size | Libdeflate size | Zlib time (s) | Libdeflate time (s) | Zlib -t1 | Libdeflate -t1
-- | -- | -- | -- | -- | -- | --
-o0 | 21166902 | 20867510 | 10.32 | 8.86 | 14.67 | 8.98
-o1 | 19989869 | 19033143 | 29.88 | 27.04 | 35.44 | 27.88
-o2 | 19606473 | 18604674 | 31.12 | 41.37 | 66.92 | 63.42
-o3 | 19369736 | 18310670 | 52.82 | 51.78 | 202.67 | 190.62
-o4 |   | 18168526 |   | 84.42 |   | 335.27
-o5 | 19369729 | 18168521 | 93.82 | 152.48 | 415.52 | 646.27
-o6 | 19369729 | 18168521 | 99.07 | 167.83 |   |  
-o3 -Z | 18042595 | | >2.5 hours | | |

Caveats:
- As libdeflate is not a streaming library, we sometimes have to guess output buffer sizes. For IDAT the decompressed size is known in advance, but for iCCP I've just made a rough estimate of the max size based on some samples. It should be generous enough but the worst that can happen is it will fail to decompress and thus won't be able to replace it with a rendering intent.
- Again due to the non-streaming nature, there is no opportunity to abort early if a timeout has been specified. Not sure how much of a problem this is.

### CODE REVIEW

**Comment by andrews05** [comment]
@shssoichiro Running `cargo fmt` will reformat all the args in main.rs (see the output of the failed test). Are you happy for this to happen?

**Comment by shssoichiro** [comment]
That's interesting. I wonder if that's the result of a Rust version bump. But yes, that's fine, please let that happen.

**Comment by andrews05** [comment]
I reverted the change to eval filters since after #458 landed it turns out filter 5 does have an impact. There are improvements to be found here which I'm continuing to explore, but they don't belong in this PR.

P.S. Do you mind if I remove/replace issue-167.png? It's super annoying when running tests 😅

**Comment by shssoichiro** [comment]
What's the problem with issue-167.png exactly?

**Comment by shssoichiro** [comment]
Ah I see. I checked on what #167 is and unfortunately the issue is related to the file being large. So I don't think there's a way around it. :sweat_smile:

**Pull request merged**
