### PR TITLE
libdeflater 0.14.0 and minor changes

### PR DESCRIPTION
**Pull request by parasew**
Updated libdeflater from 0.11.0 to 0.13.0. Zopfli now at 0.7.2. Clap from 3.2.20 -> 3.2.23. Tested extensively and here are [reproducible performance improvements and demo](https://gist.github.com/parasew/8a4fc4bd9253b7270d908e0a23a75d7e)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Just wondering, should you also update Cargo.toml since these are important updates?

BTW I could add cargo in #492 too :)

**Comment by andrews05** [comment]
Thanks for doing this! Note that the new version of libdeflate is [a bit slower](https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-116) which will affect the performance curve of levels 2-6. Hopefully it won't be too bad though.

**Comment by TPS** [comment]
@shssoichiro Is this still waiting on changes, or would you be ok to merge? 🙇🏾‍♂️

**Comment by andrews05** [comment]
Just needs tests to re-run, they should pass now.
Although... @AlexTMjugador has been making further performance improvements to zopfli - are you planning another release soon?

**Comment by AlexTMjugador** [comment]
> Although... @AlexTMjugador has been making further performance improvements to zopfli - are you planning another release soon?

I'd like to do a release once I'm done studying, applying and/or improving on some of the ideas that ECT used to speed up Zopfli without negatively affecting its compression. For the next release after that, Zopfli should have a solid single-threaded performance, so I plan to enable multi-threaded compression by focusing on the necessary traits and interface rework. I don't have a timeline for this though.

**Comment by parasew** [comment]
Updated all the crates to recent versions. The most relevant change is libdeflater 0.14.0. Everything merged and up to date with master. All tests passing.

**Comment by andrews05** [comment]
Just to provide some benchmarks for this. 290 images totalling 52,401,011 bytes.

Level | master time | PR time | master size | PR size
-- | -- | -- | -- | --
-o1 (10) | 0:29.91 | 0:29.52 | 32,264,654 | 32,200,234
-o2 (11) | 0:46.72 | 0:51.57 | 31,233,176 | 31,145,675
-o3 (11) | 1:05.93 | 1:12.00 | 31,094,663 | 31,012,645
-o4 (12) | 1:33.75 | 1:49.35 | 30,966,883 | 30,903,273

**Comment by TPS** [comment]
> @shssoichiro There's a number of PRs building up, can we get some of these moving? 🙂

&, _please_, after those, could there be a full version release w/ binaries? 🙇🏾‍♂️

**Comment by AlexTMjugador** [comment]
`indexmap` v2.0.0 was just released. It would be a good thing to update this PR to also bump that dependency, which should be relatively easy to do :smile:

**Comment by andrews05** [comment]
I realised Clap is also long out of date, with v4 being released last year. This required significant changes to update, so I posted a new PR #525 which updates everything.

**Comment by shssoichiro** [comment]
Made obsolete by #525

**Pull request closed without merging**
