### PR TITLE
handle_optimization: skip files that do not end in .png

### PR DESCRIPTION
**Pull request by matthiaskrgr**
This should help avoiding a lot of unneccessary IO.

### CODE REVIEW

**Comment by CounterPillow** [comment]
This is dumb. It should check the magic number instead of the file extension, it's perfectly valid to name your files whatever you want.

**Comment by matthiaskrgr** [comment]
Would making the Overviewer write to ````.tmp.png```` avoid issues?

**Comment by CounterPillow** [comment]
Not merging this garbage already avoids the issue.

**Comment by matthiaskrgr** [comment]
Well, feel free to provide a better solution in another pull request.

**Comment by CounterPillow** [comment]
I already provided a better solution for you: Don't feed files that aren't PNGs to oxipng. That is literally all you have to do. There is no PR to make here. Depending on file extensions is a distinctly Windows-esque thing to do.

It is worth noting that neither optipng nor zopflipng do this either.

**Comment by Argon-** [comment]
I fail to get the problem in the first place. The usage example calls oxipng with `*.png` and that's obviously the right solution for only processing files ending in .png?

**Comment by agrif** [comment]
For a concrete example of when it is possible, in a totally reasonable workflow, to have a PNG without any extension, see the [Apple guide on icon file names](https://developer.apple.com/library/content/qa/qa1686/_index.html). In particular, `iTunesArtwork` and `iTunesArtwork@2x`, which are noted:

> **Important:** iTunesArtwork icon images should be in png format, but name them without the .png extension.

If you wish to only process files ending in `.png`, you can use a `*.png` glob on the command line, or your favorite combination of `find` and `xargs`.

**Comment by matthiaskrgr** [comment]
My use case is ````oxipng -r <dir with subdirs containing images>````.
Lets say you have a git repo of a game with source files and sounds and images, it will be sufficient to just ````oxipng -r .```` in the repo root instead of ```` find . | grep "\.png$" | xargs oxipng```` which will still fail if one of the filenames happens to contain a whitespace.

Also note that ````*.png```` only works for images directly in the current directory unfortunately.

**Comment by CounterPillow** [comment]
So you want to break existing workflows because it saves you some typing?

**Comment by CounterPillow** [comment]
Also pro tip: `find . -name '*.png' -exec oxipng {} \;`

**Comment by Argon-** [comment]
I'm sorry but there's no reason to _hard code_ something like file suffixes (which are, as repeatedly stated, totally optional and arbitrary) and all just because your shell fu is not high enough.

And of course `*.png` only works for files in the current directory, that's exactly what it's supposed to do. When you want to include other directories then there are other globbings/patters available in every decent shell. Aliases and functions provide for additional comfort.

**Comment by shssoichiro** [comment]
After reading through the discussion, I think I agree that oxipng shouldn't restrict processing based on file extension. I do understand the issue, which is that oxipng loads each file entirely before determining if it is a PNG file or not. I would be willing to accept a PR that optimizes this to only load enough bytes to read the header before either returning an `Err` or continuing to load the rest of the file. In the meantime, the other users have provided workarounds for the issue that hopefully should work for you.

**Comment by CounterPillow** [comment]
I believe that reading just a few bytes would not be a sensible optimisation anyway, since I'd assume the OS reads the entire block no matter how much you read.

**Comment by shssoichiro** [comment]
It depends on the size of the file and probably the filesystem as well. Regardless of filesystem though, the file would need to be 10+ MB before there was any noticeable difference.

**Pull request closed without merging**
