### PR TITLE
Remove the concept of size bias

### PR DESCRIPTION
**Pull request by kornelski**
#198

### CODE REVIEW

**Comment by RReverser** [comment]
I'm now more confused than before :) From your explanation in https://github.com/shssoichiro/oxipng/issues/198#issuecomment-597316339, it seems that `bias` is generally a useful concept and should result in a better compression in most cases, and it's just non-determinism that has to be fixed?

**Comment by kornelski** [comment]
I think it's a useful concept in the abstract, but this implementation has caused more trouble than it's worth, so let's simplify. A better one can be added later.

**Comment by kornelski** [comment]
@shssoichiro I think it's good to merge this one

**Comment by shssoichiro** [comment]
Agreed, Sorry for delay, been busy with IRL. ^^;

**Pull request merged**
