### PR TITLE
Update Image version

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Review by shssoichiro — APPROVED** [review]
Thanks!

**Comment by shssoichiro** [comment]
Wait, I forgot that for some strange reason, the latest `image` version causes the tests to fail (#434) and unfortunately I haven't been able to figure out why...

**Comment by novacrazy** [comment]
Any update on this?

**Comment by AlexTMjugador** [comment]
I've looked into the mentioned test failure. In my workstation, I could reproduce the `issue_167` regression test failing (I couldn't confirm whether this was the failing test in that PR because its logs have expired). I've traced its cause to a memory resource consumption limit imposed by newer versions of `image` and/or the `png` crates, which makes sense given the enormous dimensions of the input image.

I've fixed the failing test by disabling resource consumption limits. I'll submit a PR with this and other updates soon.

**Comment by shssoichiro** [comment]
Superseded by #445

**Pull request closed without merging**
