### PR TITLE
Update libdeflate to v1.19

### PR DESCRIPTION
**Pull request by andrews05**
Small improvements, plus the new version no longer requires the 9 bytes of slack space.

### CODE REVIEW

**Review by AlexTMjugador — APPROVED** [review]
Thanks, this looks good. In general, how are compression ratios doing with this update?

**Comment by andrews05** [comment]
On average it's fractionally worse (see https://github.com/ebiggers/libdeflate/issues/323) but I don't think it's anything to worry about. E.g. I'm seeing 100 bytes gained in a 35MB test set.

There's no imperative to update of course.

**Comment by ace-dent** [comment]
@andrews05 this mirrors my early test results. From a few hundred images no improvement (v1.18=v1.19). Several images worse. More details to follow...

**Comment by AlexTMjugador** [comment]
Thank you both for your input! I think then that this PR is good to merge. Even if there are no significant improvements or regressions, keeping dependencies updated enables closer collaboration with upstream if the need arises, minimizing our technical debt.

**Pull request merged**
