### PR TITLE
Fixed quiet mode

### PR DESCRIPTION
**Pull request by SethDusek**
I couldn't seem to figure out why my images were coming out as corrupted even though they were fine. Turns out oxipng was still printing information about the image such as the reduction even though it was in --quiet mode and --stdout, and that broke the image.

Anyways this does some additional checking for opts.verbosity before it prints stuff

### CODE REVIEW

**Comment by shssoichiro** [comment]
Thanks for the pull request! I'll get this merged right away.

**Comment by shssoichiro** [comment]
Do you think it would be necessary/useful to enable `quiet` mode automatically whenever `stdout` is selected?

**Comment by SethDusek** [comment]
I think so, yes, since most people would probably use -q so the only thing in stdout is the image itself and nothing more so they don't have to parse it and remove the text. So I think maybe you should enable quiet mode when stdout is also enabled

**Comment by CounterPillow** [comment]
Alternatively the program could output status messages to stderr instead of stdout, like curl does.

**Comment by shssoichiro** [comment]
This is true. Maybe that would be a better option.

**Pull request merged**
