### PR TITLE
Combine palette reduction and sorting

### PR DESCRIPTION
**Pull request by andrews05**
This PR resolves the regression issue in #553.
When a palette reduction occurs, we no longer force it to be the baseline. Instead we combine it with the sorting step and only make it the baseline if sorting fails. This way we can retain the original image as the baseline in these situations without changing the number of evaluations (therefore performance remains unchanged).

The mystery of how #553's palette is weirdly optimised remains unsolved.

### CODE REVIEW

**Comment by AlexTMjugador** [comment]
This PR looks reasonable, but I guess it's a draft because it's a specific hotfix for the mentioned issue that may cause regressions or unwanted behavior changes in some edge cases?

**Comment by andrews05** [comment]
Yeah, I marked it as draft just because I want to consider my logic a little more. And indeed, it seems almost hacky for one specific image.

**Comment by Winterhuman** [comment]
I have a good number of images that show weird output size variations when OxiPNG is combined with `pngquant` if you need them for analysis (I think the differences are due to the palette optimisations like what this pull tackles), however, I suspect the new release might fix this discrepancy so I might hold off until then.

Let me know if you'd like the images anyways

**Comment by andrews05** [comment]
@Winterhuman You can try out development builds from the workflow runs if you like. Find them on the Actions page, e.g. https://github.com/shssoichiro/oxipng/actions/runs/6305282807

**Comment by Winterhuman** [comment]
Just tried out that build with some test images. Unfortunately, the output size (just `oxipng` on its own) varies widely in comparison to the current version of `oxipng`; it's hard for me to draw any conclusions on if it's better or worst than the current version.

I'll make sure to open a separate issue with what I've found

**Comment by andrews05** [comment]
@AlexTMjugador I've updated the logic here. It all comes down what we do when a palette reduction alters the image data (as opposed to just truncating the palette, for instance). In these cases, the logic goes like this:
1. We want to keep the original image as the baseline, not assume the "reduced" version is necessarily better.
2. The palette is effectively in a random order right now, neither matching the original order nor having been explicitly sorted yet. Therefore, it's unlikely to be "good" and we shouldn't waste time evaluating it until after we sort it.

It's similar to what I first posted but more correct in edge cases.

**Comment by AlexTMjugador** [comment]
Neat! I think your suggested changes are better, but I would hate to rush them into the v9 release and not think them through. For now, let's focus on releasing v9, which already has a lot of changes. A minor release can be pushed relatively quickly with this patch if we need to.

**Comment by andrews05** [comment]
Sounds good! Might help if we can get more reports of similar issues after release.

**Comment by Winterhuman** [comment]
Ran the newest force-push out of curiosity, and it's looking good!

```
Filename:		'section-tags.png'
Original Filesize:	240 bytes
PNGQuant Filesize:	186 bytes
OxiPNG Filesize:	185 bytes	<-	188 bytes
OxiPNG-ZF Filesize:	185 bytes	<-	185 bytes
Oxi-Quant Filesize:	185 bytes	<-	186 bytes
Oxi-ZF-Quant Filesize:	185 bytes	<-	185 bytes
```

Most of the results are a couple bytes of improvement, them staying the exact same, or a few bytes regressions for the non-Zopfli versions. The only notable result being this one which was one of the images included in https://github.com/shssoichiro/oxipng/issues/558 (though it's still an improvement over v8.0.0):

```
Filename:		'section-series.png'
Original Filesize:	197 bytes
PNGQuant Filesize:	160 bytes
OxiPNG Filesize:	160 bytes	<-	163 bytes
OxiPNG-ZF Filesize:	160 bytes	<-	157 bytes
Oxi-Quant Filesize:	160 bytes	<-	160 bytes
Oxi-ZF-Quant Filesize:	160 bytes	<-	157 bytes
```

**Comment by andrews05** [comment]
@Winterhuman The changes you're seeing will likely be due to the libdeflate update rather than anything in this PR. (Libdeflate is always used for evaluations, so can affect the outcome even when using Zopfli).
Good to see more consistency though.

**Comment by ace-dent** [comment]
@andrews05 @AlexTMjugador - sorry to disagree... I think this fix should be in v9 release, as it corrects a 'regression' introduced with the new palette optim code. For User's not backing up their images, they may lose an optimal palette, that may be difficult / impossible to regenerate with future fixes...

**Review by AlexTMjugador — APPROVED** [review]
Right, fair point @ace-dent. Some weeks have passed by since this PR was made, and looking at it again with fresh eyes I think it's logic is sound now. I vote we merge it!

**Pull request merged**
