### PR TITLE
Fix decoding interlaced images with height or width <= 2

### PR DESCRIPTION
**Pull request by fhanau**
Fixes decoding of interlaced images with height or width <= 2, which previously triggered an assertion as the iterator did not detect which passes are present in an image properly.

### CODE REVIEW

**Comment by fhanau** [comment]
Test file created using `convert -size 2x2 canvas:white -interlace PNG issue-175.png`: 
issue-175
https://user-images.githubusercontent.com/12156995/59851836-7ecf3700-9365-11e9-893f-92f838ec830c.png

**Comment by shssoichiro** [comment]
Thanks! Would you mind adding a regression test using that sample image? You can see how the other regression tests are set up under `tests/regression.rs`.

**Comment by fhanau** [comment]
Done!

**Comment by shssoichiro** [comment]
Thanks!

**Comment by shssoichiro** [comment]
Looks like rustup is broken at the moment, so I'm going to merge this despite the red build.

**Pull request merged**
