### PR TITLE
Add pre-commit hook declaration

### LINKED ISSUE #429: pre-commit integration
Hi

Thank you for a wonderful tool. I have just switched to using it from pngcrush and it works really well.

I use the [pre-commit](https://pre-commit.com/) framework to run tools on changed files in Git. In order to integrate it with oxipng, I set up a mirror repository: https://github.com/adamchainz/pre-commit-oxipng .

If you’d like to make it a little easier for pre-commit users, you could host the `.pre-commit-hooks.yaml` file in the oxipng repository. It’s only the one file, in order to tell pre-commit how to set up the repo and run the tool.

No pressure to add this though - the mirror repository will autoupdate with a daily GitHub Actions run.

Thank you again,

Adam

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #429.

### CODE REVIEW

**Review by shssoichiro — APPROVED** [review]
Thanks! I appreciate this a lot, as my attention has been split between a lot of different projects lately.

**Comment by adamchainz** [comment]
👍

I have no idea why the tests are failing, it's not because of this change is it?

FYI I tested this on a repo with many (already optimized) PNG files like so:

```
$ pre-commit try-repo ~/Documents/Projects/oxipng --all-files
[INFO] Initializing environment for ../oxipng.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../oxipng
    rev: 961c1548ec6daeed1edc841c0a41323ffa81e80d
    hooks:
    -   id: oxipng
===============================================================================
[INFO] Installing environment for ../oxipng.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
oxipng...................................................................Passed
```

**Comment by shssoichiro** [comment]
It looks like I need to bump the minimum Rust version, because one of the dependencies bumped theirs.

I'll do that, and then you can rebase and it should work.

**Comment by adamchainz** [comment]
Huzzah! Thank you. Tested and working great.

FYI to make this discoverable, I've submitted the hook to be displayed on the pre-commit site (https://github.com/pre-commit/pre-commit.com/pull/617) and added a note to my mirror (https://github.com/adamchainz/pre-commit-oxipng#deprecated-2022-01-15).

**Pull request merged**
