### PR TITLE
Check header of file before loading it into memory

### PR DESCRIPTION
**Pull request by emielbeinema**
This pull request seeks to provide a fix to #85 by checking only the first bytes of the file for the PNG header before loading the entire file into memory.
As this is my first PR for a Rust project, I'd be delighted to receive some feedback.

### CODE REVIEW

**Comment by shssoichiro** [comment]
Thanks! This looks good. I just left one comment that should be easy to fix.

**Comment by emielbeinema** [comment]
Thanks for the feedback! I can't seem to find the comment you mention, though. Have I overlooked something?

**Comment by shssoichiro** [comment]
Sorry, I guess I had to hit "Submit Review". I'm not use to Github's way of doing PR comments, so that was probably my fault.

**Comment by emielbeinema** [comment]
Thanks again! I followed your suggestion and it does look cleaner :)

**Comment by shssoichiro** [comment]
Thanks!

**Pull request merged**
