### PR TITLE
Workaround weird regression with &[u8] and zopfli

### LINKED ISSUE #579: Probably regression in v9.0.0 compared to v8.0.0, compression became worse
This is the command that was used to convert an album of anime screenshots:
`oxipng.exe --verbose --threads 8 --alpha --force --interlace 1 -f 0-9 --zopfli --strip safe --preserve *.png`

Here is the output from new `oxipng-9.0.0-x86_64-pc-windows-msvc.zip`:

```
Processing: HenSuki.png
    1920x2290 pixels, PNG format
    8-bit RGB, non-interlaced
    IDAT size = 9382252 bytes
    File size = 9384075 bytes
Reducing image to 8-bit RGB, interlaced
Trying: Brute
Found better combination:
    zc = zopfli  f = Brute     6534426 bytes
    IDAT size = 6534426 bytes (2847826 bytes decrease)
    file size = 6534517 bytes (2849558 bytes = 30.37% decrease)
6534517 bytes (30.37% smaller): HenSuki.png
```

And here is the output from old `oxipng-8.0.0-x86_64-pc-windows-msvc.zip`
```
Processing: HenSuki.png
preserving metadata: Some(Metadata { file_type: FileType(FileType { attributes: 32, reparse_tag: 0 }), is_dir: false, is_file: true, permissions: Permissions(FilePermissions { attrs: 32 }), modified: Ok(SystemTime { intervals: 133445895491882136 }), accessed: Ok(SystemTime { intervals: 133445907278923468 }), created: Ok(SystemTime { intervals: 133445907278873930 }), .. })
    1920x2290 pixels, PNG format
    3x8 bits/pixel, RGB (non-interlaced)
    IDAT size = 9382252 bytes
    File size = 9384075 bytes
Reducing image to 3x8 bits/pixel, RGB (interlaced)
Evaluating: 10 filters
Trying: Brute
    zc = 0  f = Brute     6468101 bytes
Found better combination:
    zc = 0  f = Brute     6468101 bytes
    IDAT size = 6468101 bytes (2914151 bytes decrease)
    file size = 6468192 bytes (2915883 bytes = 31.07% decrease)
attempting to set file times: atime: FileTime { seconds: 13344590727, nanos: 892346800 }, mtime: FileTime { seconds: 13344589549, nanos: 188213600 }
Output: HenSuki.png
```
I am attaching this image along with its compressed versions in zip here:
[HenSuki.zip](https://github.com/shssoichiro/oxipng/files/13373412/HenSuki.zip)

This problem is happening with other similar images too, which were not specifically crafted to trick oxipng. Actually, the new version was checked against images that were already compressed by the old version to see if it would improve the compression ratio, but instead of `0 bytes decrease`/`0.00% decrease` it showed `larger`/`increase`.

You can find the full album compressed with the old version here:
https://telegra.ph/HenSuki-03-08
The problem happens on all images except for one (that depicts a letter and has large similarly-colored areas).

### PR DESCRIPTION
**Pull request by andrews05**
Fixes #579. In lack of a proper understanding of what's going on here and why the issue is happening, this workaround will do for now.

### CODE REVIEW

**Comment by AlexTMjugador** [comment]
I'd like to fix this in the Zopfli crate itself instead, but let's keep this PR open in case I'm unable to do so in a timely fashion.

**Comment by andrews05** [comment]
Sounds good. I'm thinking we should do a point release once this is fixed.

**Comment by XhmikosR** [comment]
@andrews05 could you please rebase the branch so that I can grab the latest CI build for testing? Thanks!

**Comment by andrews05** [comment]
@XhmikosR Done

**Comment by andrews05** [comment]
Oh, looks like there are some new clippy lints I need to fix. I’ll try and sort that soon…

**Comment by andrews05** [comment]
Success!

**Comment by XhmikosR** [comment]
@andrews05 just my 2 cents. The clippy fixes could go into master separately, but this makes me wonder how come you guys are hitting this inconsistency. I believe you need to enable the repo option for branches to always be up to date so that you catch such issues before landing something in master.

**Comment by AlexTMjugador** [comment]
I think the Clippy lint fixes should have been pushed to the main branch separately, so that this and other PRs could be rebased on top of those changes and benefit them all. But I'm doing the cherry-picking and rebasing now, so no worries here.

> What do you think, will you have time to investigate or shall we just use this for now?

Next week I finally have some days off which I could use to dedicate some time to open source work like this, but no promises :slightly_smiling_face:

**Comment by ace-dent** [comment]
Hey gang... any chance of rebasing to main, to regenerate the CI artefacts? 🙏🏻

**Comment by andrews05** [comment]
@ace-dent done. Let me know your observations with and without this patch.

**Comment by ace-dent** [comment]
@andrews05 - nice! Thanks!

**Comment by XhmikosR** [comment]
@andrews05 could you please rebase the branch? TIA!

**Comment by andrews05** [comment]
@XhmikosR Done. Are you finding any improvement from this change?

**Comment by XhmikosR** [comment]
Thanks!

I need to test again with new files because I've already had a run with this patch in the past. I remember there were some small savings, but I'll try to get back to you with numbers.

Maybe @ace-dent has a recent benchmark.

**Comment by ace-dent** [comment]
@XhmikosR I won't be in position to do thorough testing for a few weeks.
If you want an *highly* optimised test set, you can try re-running on all `*.png` images in [this repo](https://github.com/KolibriOS/kolibrios).

**Comment by XhmikosR** [comment]
I tested @ace-dent's repos and there was no difference between 9.1.2 and this PR, although there were improvements:

```
Before: 3,31 MB (3.475.236 bytes)
After:  3,25 MB (3.409.474 bytes).
```

But I tested a few images created with Firefox's built-in screenshot tool and this PR resulted in consistently better compression.

OS: Windows 11 (Pro) x86_64 / WIN32_NT 10.0.22631.3880 (23H2)

```
9.1.2:
E:\Downloads\Internet Downloads>oxipng -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png"
Processing: Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png
110394 bytes (62.10% smaller): Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png

PR:
E:\Downloads\Internet Downloads>oxipng -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png"
Processing: Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png
108665 bytes (62.69% smaller): Screenshot 2024-07-14 at 14-38-25 Tor Project Success.png

---
9.1.2:
E:\Downloads\Internet Downloads>oxipng -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png"
Processing: Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png
127783 bytes (49.18% smaller): Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png

PR:
E:\Downloads\Internet Downloads>oxipng -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png"
Processing: Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png
123321 bytes (50.95% smaller): Screenshot 2024-07-14 at 17-57-00 Workaround weird regression with & u8 and zopfli by andrews05 · Pull Request #595 · shssoichiro_oxipng.png

---
9.1.2:
E:\Downloads\Internet Downloads>oxipng912 -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png"
Processing: Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png
117701 bytes (55.77% smaller): Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png

PR:
E:\Downloads\Internet Downloads>oxipng -o max -Z --preserve -s --fix --alpha "Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png"
Processing: Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png
116135 bytes (56.36% smaller): Screenshot 2024-07-14 at 18-11-25 Release v9.1.2 · shssoichiro_oxipng.png
```

**Comment by andrews05** [comment]
@XhmikosR Nice, thanks for the info!

**Comment by XhmikosR** [comment]
@andrews05 could you please rebase the branch one more time?

BTW, any reason why this hasn't landed yet? I mean, I know it doesn't fix the root cause but it does yield better compression.

Thanks!

**Comment by AlexTMjugador** [comment]
> I guess we're still hoping @AlexTMjugador can investigate the root cause sometime 😅

I clearly didn't have the chance to delve into the matter that week I planned to :sweat_smile:

Researching a more proper fix for this behavior should be relatively straightforward though, nothing too complicated for an afternoon or so. The problem being that almost always another thing to do appears in my afternoons... But I'd like for me or someone else to get around to it, eventually.

**Pull request merged**
