### PR TITLE
Exclude more files from the published crate

### PR DESCRIPTION
**Pull request by musicinmybrain**
There was an incorrect glob `bench/*` that was doing nothing, since the benchmarks are in `benches/`; when I corrected it to `benches/*`, `cargo publish --dry-run` failed:

```
error: failed to verify package tarball

Caused by:
  failed to parse manifest at `/home/ben/src/forks/oxipng/target/package/oxipng-9.0.0/Cargo.toml`

Caused by:
  can't find `zopfli` bench at `benches/zopfli.rs` or `benches/zopfli/main.rs`. Please specify bench.path if you want to use a non-default path.
```

…so I stopped trying to exclude the benchmarks from published crates at all.

-----

Then, I added `Dockerfile`, `index.html`, and `scripts/` to the list of paths to exclude from published crates.

Finally, I added some unnecessary “dotfiles” to the list of paths to exclude from published crates.

-----

Some of this was suggested in a [package review for Fedora Linux](https://bugzilla.redhat.com/show_bug.cgi?id=2259760).

After the PR:

```
$ cargo package --list
.cargo/config.toml
.cargo_vcs_info.json
CHANGELOG.md
Cargo.lock
Cargo.toml
Cargo.toml.orig
LICENSE
MANUAL.txt
README.md
benches/deflate.rs
[…]
benches/zopfli.rs
src/atomicmin.rs
[…]
src/sanity_checks.rs
$ cargo publish --dry-run
[…]
   Compiling oxipng v9.0.0 (/home/ben/src/forks/oxipng/target/package/oxipng-9.0.0)
    Finished dev [optimized + debuginfo] target(s) in 15.76s
    Packaged 37 files, 255.4KiB (61.6KiB compressed)
   Uploading oxipng v9.0.0 (/home/ben/src/forks/oxipng)
warning: aborting upload due to dry run
```

### CODE REVIEW

**Comment by andrews05** [comment]
Thanks for this, it sounds sensible.
Just one comment: The index.html file seems to be for a very old set of docs that no longer exists. We should just delete this file.

**Comment by musicinmybrain** [comment]
> Thanks for this, it sounds sensible. Just one comment: The index.html file seems to be for a very old set of docs that no longer exists. We should just delete this file.

Thanks for  the suggestion! I removed `index.html` from the repo and from the `excludes`.

**Review by andrews05 — APPROVED** [review]
Looks good to me! Can merge once @AlexTMjugador also approves.

**Review by AlexTMjugador — APPROVED** [review]
Thank you for the PR, it looks good to me too! Let's merge it then :rocket:

**Pull request merged**
